export type ServiceContent = {
  what: string;
  benefits: string[];
  considerations: string[];
  process: string;
  avgCost: string;
  candidate: string;
  faqs: { q: string; a: string }[];
};

function defaultContent(name: string): ServiceContent {
  return {
    what: `${name} is a service offered by interior design studios across the country. A designer will walk your space, learn how you live or work in it, and build a plan covering layout, materials, furniture and lighting.`,
    benefits: [
      "A layout and material plan made for your actual space",
      "Access to trade-only furniture, fabric and lighting sources",
      "Fewer costly mistakes and returns",
      "One point of contact between you, contractors and vendors",
    ],
    considerations: [
      "Fees are quoted flat, hourly, or cost-plus — ask which model applies",
      "Lead times on custom furniture can run 8–16 weeks",
      "Trade discounts vary by vendor and may be shared or retained",
      "Confirm who manages installation, delivery and punch list",
    ],
    process: `Most studios start with a paid consultation, then move through concept and mood boards, space planning, material and furniture selection, procurement, and finally installation and styling.`,
    avgCost: `Fees depend on scope, square footage and city. Studios typically charge a flat design fee, an hourly rate of roughly $100–$300, or a cost-plus percentage on furnishings. Request quotes from a few studios to compare.`,
    candidate: `Anyone who wants a considered result and would rather not manage sourcing, trades and logistics alone. Even a single consultation can save money on a project you plan to run yourself.`,
    faqs: [
      { q: `How long does ${name.toLowerCase()} take?`, a: `Timelines depend on scope. A single room typically runs 8–16 weeks including procurement; whole-home and renovation work often runs 6–18 months.` },
      { q: `What does ${name.toLowerCase()} cost?`, a: `Studios quote flat fees, hourly rates or a percentage of the furnishings budget. Every listing on Intearior shows a typical project budget so you can shortlist studios at your scale.` },
      { q: `Do I need to have a budget ready?`, a: `A rough range is enough to start. Designers use it to steer sourcing, so an honest number leads to a better fit.` },
    ],
  };
}

const OVERRIDES: Record<string, ServiceContent> = {
  "full-home-design": {
    what: "Full-home design covers every room in a house or apartment — layout, finishes, built-ins, furniture, lighting, textiles and art — coordinated into one consistent scheme rather than room-by-room decisions made months apart.",
    benefits: [
      "A single coherent palette and material story across the home",
      "Efficient sourcing — one procurement round rather than several",
      "Better coordination with architects, builders and trades",
      "A long-term plan you can phase over years if the budget requires",
    ],
    considerations: [
      "Design fees are usually quoted before the furnishings budget is known",
      "Living on site during install is disruptive — plan storage and staging",
      "Custom upholstery and casegoods commonly run 12–20 weeks",
      "Agree early whether the studio holds the trade discount or passes it on",
    ],
    process: "Discovery and lifestyle interview, whole-home space plan, concept presentation per floor, finish and furniture specification, one consolidated procurement round, then a phased install and final styling day with photography.",
    avgCost: "Full-home projects commonly start around $30k in design fees for a mid-size home, with furnishings budgets typically running $75k and up depending on scope and city.",
    candidate: "Owners of a newly bought or newly built home who want the whole property resolved at once, and anyone tired of rooms that don't speak to each other.",
    faqs: [
      { q: "Can full-home design be phased over time?", a: "Yes. Most studios will design the whole house up front, then install in phases — public rooms first, bedrooms later — so the scheme stays consistent even if spending is spread across years." },
      { q: "Do I need to move out during a full-home project?", a: "Only if construction is involved. Furnishing-only projects are installed over a few days; a gut renovation usually requires moving out for the build phase." },
      { q: "How much of the budget goes to furniture versus design fees?", a: "As a rule of thumb, design fees land at roughly 20–30% of the furnishings budget on full-home work, though flat-fee studios quote independently of what you spend." },
    ],
  },
  "kitchen-design": {
    what: "Kitchen design covers layout and workflow, cabinetry and millwork, counters and backsplash, appliance planning, lighting, and the electrical and plumbing coordination that goes with them.",
    benefits: [
      "Workflow planned around how you actually cook and entertain",
      "Cabinet and appliance specs checked against each other before ordering",
      "A coordinated lighting, ventilation and electrical plan",
      "Materials chosen for wear and cleaning, not just looks",
    ],
    considerations: [
      "Appliance selections must be locked before cabinetry is fabricated",
      "Semi-custom cabinetry runs 8–12 weeks; full custom often 14–20",
      "Moving plumbing or gas lines adds permit and structural cost",
      "Stone slabs should be selected in person — no two are identical",
    ],
    process: "Measure and workflow interview, two or three layout options, appliance and cabinetry specification, finish and hardware selection, shop-drawing review with the cabinet maker, then site visits through demolition, install and template.",
    avgCost: "Kitchen design fees typically run $5k–$20k. Construction and cabinetry usually run $30k–$150k+ depending on scope, cabinetry grade and appliances.",
    candidate: "Anyone remodelling a kitchen where walls, plumbing or cabinetry change — the cost of a layout mistake here is far higher than the design fee.",
    faqs: [
      { q: "Do I need a kitchen designer if the showroom does a layout?", a: "Showroom layouts are made to sell their cabinet line. An independent designer specifies across brands, coordinates lighting and electrical, and represents you at the site." },
      { q: "How long is a kitchen without a working kitchen?", a: "Plan for 8–14 weeks of downtime on a full remodel once demolition starts, assuming cabinetry arrived on schedule. Most designers help you set up a temporary kitchen." },
      { q: "Which comes first — appliances or cabinets?", a: "Appliances. Cabinet openings are cut to appliance dimensions, so specifying the range, hood and fridge is one of the first decisions." },
    ],
  },
  "bathroom-design": {
    what: "Bathroom design covers fixture layout, waterproofing and tile detail, vanity and storage design, lighting and mirrors, ventilation, and accessible or ageing-in-place adjustments where needed.",
    benefits: [
      "A layout that clears door swings, glass panels and code setbacks",
      "Tile layouts drawn so cuts land in sensible places",
      "Fixture specs matched to your actual water pressure and valve type",
      "Ventilation and lighting planned to stop mould and bad mirrors",
    ],
    considerations: [
      "Waterproofing detail matters more than any finish you can see",
      "Shower valves and rough-in parts must be on site before tiling",
      "Slab-on-grade homes limit where drains can move",
      "Natural stone in wet areas needs sealing and ongoing care",
    ],
    process: "Site measure, fixture and layout options, tile and stone selection, lighting and mirror plan, plumbing rough-in drawings for the contractor, then tile layout supervision and a final punch list.",
    avgCost: "Bathroom design fees typically run $3k–$12k, with construction commonly $20k–$80k depending on size and finishes.",
    candidate: "Anyone moving fixtures, redoing a wet area, or converting a tub to a curbless shower — all cases where drawings prevent expensive rework.",
    faqs: [
      { q: "Can a small bathroom justify a designer?", a: "Often yes — small rooms have the least tolerance for error, and a few inches of vanity depth or a badly placed valve is hard to undo." },
      { q: "How long does a bathroom remodel take?", a: "Typically 4–8 weeks of construction after a 4–8 week design and ordering phase, longer if custom glass or stone is involved." },
      { q: "Is a curbless shower always possible?", a: "It depends on floor structure. Joisted floors usually allow recessing; slab foundations may need a shallow ramp or a raised floor build-up instead." },
    ],
  },
  "living-dining": {
    what: "Living and dining design resolves the rooms you host in — seating layout and conversation distances, rug and table sizing, lighting layers, media and storage, and window treatments that work with the architecture.",
    benefits: [
      "Seating scaled and spaced for real conversation, not showroom photos",
      "Correct rug and dining table sizes for the room's dimensions",
      "Layered lighting instead of a single overhead fixture",
      "Storage and media integrated rather than added later",
    ],
    considerations: [
      "Sofa and sectional lead times commonly run 10–16 weeks",
      "Measure stair turns and lift dimensions before ordering large pieces",
      "Open-plan rooms need zoning or they read as a furniture showroom",
      "Performance fabrics are worth it in households with kids or pets",
    ],
    process: "Room measure and use interview, furniture plan with clearances drawn, concept board, upholstery and rug selection, lighting and window treatment specification, then a single install and styling day.",
    avgCost: "Design fees for a combined living and dining scheme typically run $3.5k–$12k, with furnishings commonly $20k–$80k depending on upholstery grade and whether pieces are custom.",
    candidate: "People whose main rooms feel unresolved — furniture that doesn't fit, no place to put a drink, or an open plan that never settled into zones.",
    faqs: [
      { q: "What size rug should a living room have?", a: "Large enough for at least the front legs of every seat to sit on it. Designers size the rug to the seating group, not to the room." },
      { q: "How far apart should sofas and chairs sit?", a: "Roughly 7–9 feet between facing seats keeps conversation comfortable; beyond that the room feels like a waiting area." },
      { q: "Can living and dining share one scheme in an open plan?", a: "Yes — one palette across both, with rugs, lighting and a change in furniture height marking each zone." },
    ],
  },
  "bedroom-design": {
    what: "Bedroom design covers bed placement and circulation, storage and wardrobe planning, layered and controllable lighting, blackout and acoustic treatment, and the textiles that make the room sleep well.",
    benefits: [
      "Light control planned for actual sleep, not just decoration",
      "Storage sized to the wardrobe you own",
      "Bedside lighting and outlets in reachable positions",
      "A calm palette and textile plan that layers over the seasons",
    ],
    considerations: [
      "Blackout drapery needs a return or wraparound track to stop light leaks",
      "Headboard and bed frame lead times often run 8–14 weeks",
      "Wall-mounted reading lights need electrical planning before painting",
      "Rug placement around a bed is measured, not eyeballed",
    ],
    process: "Sleep and storage interview, furniture layout, palette and textile board, lighting and window treatment specification, then delivery, install and bed styling.",
    avgCost: "Design fees typically run $2.5k–$8k per bedroom, with furnishings commonly $8k–$35k depending on custom upholstery and joinery.",
    candidate: "Anyone whose bedroom became storage-by-default, or who sleeps badly because of light, noise or a room that never got finished.",
    faqs: [
      { q: "Where should the bed go?", a: "Usually on the longest uninterrupted wall with clear access on both sides, away from door swings and direct HVAC flow — designers test this on plan before anything is ordered." },
      { q: "Are blackout blinds or curtains better?", a: "Curtains on a wraparound track block edge light better; blinds are neater. Many bedroom schemes use both — a roller behind full-length drapery." },
      { q: "What rug size works in a bedroom?", a: "Either one large rug extending 2–3 feet beyond the bed on three sides, or runners on each side — the in-between size is what usually looks wrong." },
    ],
  },
  "home-office": {
    what: "Home office design covers desk position and ergonomics, video-call lighting and background, acoustic treatment, cable and power management, storage, and — in shared homes — separating work from the rest of the house.",
    benefits: [
      "A desk position that works for daylight and camera framing",
      "Ergonomics specified rather than improvised",
      "Cables, power and networking planned into the joinery",
      "Acoustic treatment so calls don't echo",
    ],
    considerations: [
      "Windows directly behind a desk make video calls unusable",
      "Built-in desks need power and data before the joinery is fixed",
      "Task chairs are the one place not to economise",
      "Check whether a home office affects home insurance or tax treatment",
    ],
    process: "Work-pattern interview, desk and storage layout, lighting and acoustics plan, joinery or furniture specification, cable and power schedule for the electrician, then install and setup.",
    avgCost: "Design fees typically run $2k–$7k. Furnishing a home office commonly runs $5k–$30k, with built-in joinery at the upper end.",
    candidate: "Full-time remote workers, people running a business from home, and households where two people take calls at once.",
    faqs: [
      { q: "Where should a desk sit relative to the window?", a: "Perpendicular to it. Facing the window causes glare; backing onto it silhouettes you on camera." },
      { q: "Is built-in joinery worth it over freestanding furniture?", a: "In small or awkward rooms, usually yes — it recovers depth and hides cables. In a large room, freestanding pieces are cheaper and can move with you." },
      { q: "How do I stop calls echoing?", a: "Soft surfaces: a rug, lined curtains, upholstered seating, and a bookcase with irregular contents. Designers specify these as an acoustic layer, not just decoration." },
    ],
  },
  "outdoor-patio": {
    what: "Outdoor and patio design covers terraces, decks, courtyards and balconies — paving and level changes, outdoor kitchens and fire features, shade, exterior lighting, planting containers and weather-rated furniture.",
    benefits: [
      "Materials specified for your climate, sun exposure and drainage",
      "Shade and wind handled so the space is usable more of the year",
      "Outdoor lighting zoned and controlled from inside",
      "Furniture chosen for real UV, rain and salt exposure",
    ],
    considerations: [
      "Drainage and waterproofing decisions come before any finish",
      "HOAs, coastal rules and setbacks often restrict structures",
      "Outdoor kitchens need gas, water and power runs planned early",
      "Teak, aluminium, rope and performance fabric all age differently",
    ],
    process: "Site and sun-path review, layout and zoning, hardscape and material selection, shade and lighting plan, furniture and planting specification, then coordination with landscape or hardscape contractors through install.",
    avgCost: "Design fees typically run $3k–$12k. Build and furnishing budgets vary widely — a furnished terrace often lands at $15k–$60k, while outdoor kitchens and structures push well beyond that.",
    candidate: "Anyone with an unused terrace, deck or courtyard, and homeowners in mild climates who want the outdoor room to work as hard as the indoor ones.",
    faqs: [
      { q: "What outdoor furniture actually lasts?", a: "Powder-coated aluminium, teak and all-weather rope with solution-dyed acrylic cushions hold up best. Cheap steel and untreated softwood rarely survive two seasons." },
      { q: "Do I need permits for a patio project?", a: "Paving at grade usually doesn't; roofs, pergolas over a certain size, gas lines and electrical almost always do. Your designer will flag what needs a permit." },
      { q: "Can a small balcony be worth designing?", a: "Yes — small outdoor spaces need the most careful furniture scaling, drainage-safe flooring and weight limits checked against building rules." },
    ],
  },
  "commercial-office": {
    what: "Commercial and office design covers space planning and workplace zoning, acoustics, furniture systems, branded environments, and compliance with building, fire and accessibility codes.",
    benefits: [
      "Headcount and growth planned into the floor plate",
      "Acoustic zoning between focus, collaboration and call space",
      "Contract-grade furniture specified with real warranties",
      "Documentation coordinated with landlord and building management",
    ],
    considerations: [
      "Commercial work often requires stamped drawings and code review",
      "Many states register or license designers for commercial interiors",
      "Contract furniture lead times are long — order well ahead of move-in",
      "Landlord fit-out rules, hours and insurance requirements shape the schedule",
    ],
    process: "Headcount and workflow programming, test fits, landlord approval, construction documentation, contract furniture specification and bid, then site administration, install and day-one support.",
    avgCost: "Commercial fees are often quoted per square foot — commonly $5–$20/sq ft for design services, separate from construction and furniture.",
    candidate: "Companies relocating, growing into new space, or bringing hybrid teams back into an office that no longer suits how they work.",
    faqs: [
      { q: "How much space per employee should we plan?", a: "Modern hybrid workplaces commonly plan 100–150 usable sq ft per person including shared space, but the right number depends on your attendance pattern, not a benchmark." },
      { q: "Who signs off the drawings?", a: "Depending on jurisdiction and scope, an architect or registered interior designer stamps the permit set. Your designer will tell you which applies before you sign a lease." },
      { q: "How early should we start before a lease begins?", a: "Six to nine months for a full fit-out is typical once furniture lead times and permitting are accounted for." },
    ],
  },
  "retail-hospitality": {
    what: "Retail and hospitality design shapes commercial spaces built to be experienced — store layout and customer flow, fixtures and display, hotel and lounge interiors, materials that survive heavy public use, and brand expressed spatially.",
    benefits: [
      "Circulation designed around dwell time and sightlines to product",
      "Fixtures built for restocking and merchandising changes",
      "Finishes rated for commercial traffic and cleaning regimes",
      "A design language that can be rolled out to further locations",
    ],
    considerations: [
      "Occupancy, egress and accessibility codes drive layout decisions",
      "Landlord and mall design review can add months",
      "Lighting quality directly affects how product reads and sells",
      "Trading during construction requires phased or overnight works",
    ],
    process: "Brand and customer-journey workshop, concept design, layout and fixture packages, material and lighting specification, permit documentation, then contractor coordination, install and merchandising handover.",
    avgCost: "Design fees are commonly quoted per square foot or as a flat concept-plus-documentation fee; small-format retail concepts often start around $15k, with build costs typically $100–$400/sq ft.",
    candidate: "Independent retailers, restaurateurs, hoteliers and multi-site operators who need a space that both trades well and photographs well.",
    faqs: [
      { q: "How is retail design different from residential?", a: "It is driven by commercial performance and code — customer flow, sightlines, durability, occupancy and accessibility — with aesthetics serving those goals." },
      { q: "Can a concept be reused across locations?", a: "Yes. Many studios deliver a brand standards or kit-of-parts document so later stores repeat the concept at lower design cost." },
      { q: "Do we need to close during the fit-out?", a: "Not always. Phased works and overnight installation are common, though they raise labour cost and lengthen the schedule." },
    ],
  },
  "home-staging": {
    what: "Home staging prepares a property for sale — editing, rearranging or renting furniture and styling each room so buyers read the space quickly, both in listing photography and on a walkthrough.",
    benefits: [
      "Rooms that photograph well for the listing, which is where buyers decide",
      "Purpose given to awkward or empty spaces",
      "Personal clutter edited out so buyers can project themselves in",
      "Faster time on market and stronger perceived condition",
    ],
    considerations: [
      "Rental inventory is billed monthly — budget for the full listing period",
      "Staging is not repair; obvious defects should be fixed first",
      "Occupied staging works with your furniture and has real limits",
      "Book early — good stagers are scheduled weeks ahead in peak season",
    ],
    process: "Walkthrough and written report, decluttering and repair recommendations, furniture plan, inventory delivery and installation ahead of the photography date, then de-staging after closing.",
    avgCost: "Consultations typically run $200–$600; full staging with rented inventory commonly runs $2k–$8k per month depending on the size of the home.",
    candidate: "Sellers listing a vacant property, sellers whose furniture dates the house, and agents preparing higher-value listings for photography.",
    faqs: [
      { q: "Does staging actually change the sale price?", a: "Agents widely report faster sales and stronger offers on staged listings, but results vary by market. Ask a stager for recent local examples rather than national statistics." },
      { q: "Should I stage every room?", a: "No. Most stagers focus on the rooms buyers weigh most — living, kitchen, primary bedroom and the entry — and leave secondary rooms lightly dressed." },
      { q: "Can I stage a home I still live in?", a: "Yes, that's occupied staging: heavy editing, rearranging what you own, plus a few rented pieces and accessories." },
    ],
  },
  "e-design": {
    what: "E-design (virtual design) delivers a complete room plan remotely — you supply measurements and photos, and the designer returns a floor plan, mood board, shopping list and setup instructions as a package.",
    benefits: [
      "Far lower cost than full-service design",
      "Available from any studio in the country, not just local ones",
      "You buy and install on your own schedule",
      "A great fit for single rooms, rentals and first apartments",
    ],
    considerations: [
      "Measurement accuracy is your responsibility — mistakes flow through the plan",
      "Ordering, returns and assembly are usually yours to manage",
      "Trade-only pieces may not be available through an e-design package",
      "Revision rounds are limited; check how many are included",
    ],
    process: "Questionnaire and photo upload, measurement submission, concept board, revision round, then a final package with floor plan, product list with links, and an install guide.",
    avgCost: "E-design packages typically run $300–$2,500 per room depending on the number of revisions and the depth of the deliverables.",
    candidate: "Confident DIY-ers, renters, people outside major metros, and anyone who wants professional direction without a full-service fee.",
    faqs: [
      { q: "How is e-design different from full-service design?", a: "You do the buying, delivery coordination and installation. The designer provides the plan, the specifications and the shopping list." },
      { q: "What do I need to provide?", a: "Accurate room dimensions including ceiling height, window and door positions, photos from each corner, and a clear budget." },
      { q: "What if something is out of stock?", a: "Most packages include a substitution allowance or one revision round; ask before booking how out-of-stock items are handled." },
    ],
  },
  "space-planning": {
    what: "Space planning is the drawing-board layer of design — testing how rooms, circulation, furniture and storage fit before any finish is chosen, often alongside architectural changes.",
    benefits: [
      "Layout options tested on paper instead of after demolition",
      "Circulation, door swings and clearances verified to code",
      "Furniture sized to the plan before anything is ordered",
      "A drawing set your architect or builder can actually use",
    ],
    considerations: [
      "Structural walls, plumbing stacks and windows limit what can move",
      "Space planning alone doesn't include finish or furniture selection",
      "Accurate as-built measurements are essential — laser survey is worth it",
      "Some plan changes require permits even without an addition",
    ],
    process: "As-built survey, programming interview, two or three layout options with pros and cons, refinement of the chosen scheme, then dimensioned plans and furniture layouts issued for construction or purchasing.",
    avgCost: "Space planning is often billed hourly at $100–$250 or as a flat fee of roughly $1.5k–$6k per floor depending on size and complexity.",
    candidate: "Anyone about to renovate, buy furniture for an empty home, or knock walls around — and anyone with a room that never quite works despite nice furniture.",
    faqs: [
      { q: "Is space planning the same as an architect's work?", a: "No. Architects handle structure, envelope and permits; space planners resolve how the interior is used and furnished. On larger projects the two work together." },
      { q: "Can I hire someone just for a floor plan?", a: "Yes — many studios sell space planning as a standalone deliverable, and it's the highest-value first step if the budget is tight." },
      { q: "Do I need measured drawings?", a: "The designer will usually measure. If you supply your own, dimensions must include ceiling heights, window sill heights and structural elements." },
    ],
  },
  "custom-millwork": {
    what: "Custom millwork is designed, purpose-built joinery — bookcases, panelling, banquettes, mudroom benches, window seats and integrated storage drawn for a specific wall and made by a fabricator.",
    benefits: [
      "Storage that uses awkward depths, angles and ceiling height",
      "Architectural character in rooms that lack it",
      "Materials and hardware specified for daily use",
      "Details resolved on shop drawings before anything is cut",
    ],
    considerations: [
      "Fabrication runs 8–16 weeks after shop drawings are approved",
      "Site conditions must be measured after framing, not before",
      "Painted, stained and veneered finishes age very differently",
      "Site-finished pieces need dust protection and drying time",
    ],
    process: "Concept and elevation sketches, material and hardware selection, fabricator bidding, shop drawing review, site measure, fabrication, then installation and finishing.",
    avgCost: "Design fees are typically $1.5k–$8k per element or hourly. Fabrication and installation commonly run $250–$900 per linear foot depending on material and complexity.",
    candidate: "Homes with tricky alcoves, high ceilings or too little storage, and anyone who wants built-in character rather than another freestanding cabinet.",
    faqs: [
      { q: "Is custom millwork worth it over IKEA-style systems?", a: "When the wall is irregular, the ceiling is tall, or the piece is a focal point, yes. For a standard-depth closet, a hacked stock system is often the smarter spend." },
      { q: "Painted or stained?", a: "Paint hides seams and suits period detail; stain and veneer show grain but need matched material across the run. Your designer will specify grade accordingly." },
      { q: "Who installs it?", a: "Usually the fabricator's own crew. The designer reviews shop drawings, checks the site measure, and inspects the install before final payment." },
    ],
  },
  "lighting-design": {
    what: "Lighting design plans how a space is lit at every hour — ambient, task, accent and decorative layers, colour temperature and dimming, fixture selection, and the switching and control plan that goes with it.",
    benefits: [
      "Layered light instead of one glaring ceiling fixture per room",
      "Consistent colour temperature and high colour rendering",
      "Dimming and scenes so rooms work morning and evening",
      "Fixture positions coordinated with joinery and art before wiring",
    ],
    considerations: [
      "Circuits and switch positions must be set before drywall",
      "Cheap dimmers cause flicker and buzz with LED sources",
      "Recessed downlights alone flatten a room — layers matter",
      "Smart control systems need commissioning, not just installation",
    ],
    process: "Room-by-room use review, reflected ceiling plan, fixture and lamp specification, switching and dimming schedule for the electrician, then aiming, focusing and scene setting after install.",
    avgCost: "Lighting design is commonly billed hourly at $125–$300 or as a flat fee of $2k–$10k for a home; decorative fixtures and controls are a separate budget.",
    candidate: "Anyone renovating while the walls are open, plus homeowners whose rooms feel harsh at night or whose art and joinery are unlit.",
    faqs: [
      { q: "What colour temperature should I use at home?", a: "Most residential schemes sit at 2700K, sometimes 3000K in kitchens and baths, kept consistent within sightlines. Mixed temperatures are the most common lighting mistake." },
      { q: "How many downlights does a room need?", a: "Fewer than most plans show. A good scheme mixes a small number of well-placed downlights with wall, table and accent light rather than a grid of ceiling holes." },
      { q: "Are smart lighting controls worth it?", a: "If you want scenes, yes — but choose a system your electrician can service, and budget for commissioning time, not just hardware." },
    ],
  },
  "window-treatments": {
    what: "Window treatment design specifies drapery, shades, blinds, shutters and motorisation — fabric, lining, heading style, hardware, mounting and light control — measured and made for each opening.",
    benefits: [
      "Light and privacy controlled without losing the view",
      "Windows made to look taller and rooms better proportioned",
      "Fabrics chosen for fade resistance on the sunniest elevations",
      "Motorisation planned with power in the right place",
    ],
    considerations: [
      "Measuring is unforgiving — professional measure is standard",
      "Custom drapery runs 6–12 weeks from fabric approval",
      "Motorised hardware needs power or a charging plan before install",
      "Blackout linings need returns or side channels to stop light leaks",
    ],
    process: "Window survey and light-control brief, fabric and hardware selection, professional measure, workroom fabrication, then installation, dressing and steaming.",
    avgCost: "Specification is often folded into a design fee or billed hourly. Fabricated treatments commonly run $600–$3,000 per window installed, higher with motorisation or wide spans.",
    candidate: "Anyone with bare windows in a finished home, rooms with heat or glare problems, and homeowners who bought furniture but never resolved the windows.",
    faqs: [
      { q: "How high should drapery be hung?", a: "Usually close to the ceiling or the top of the wall band, with the rod extending well past the frame so the stack clears the glass." },
      { q: "Shades or curtains?", a: "Shades give clean light control in tight reveals; curtains add softness, warmth and acoustic benefit. Many rooms use both layered together." },
      { q: "Is motorisation worth the cost?", a: "For tall, wide or hard-to-reach windows, yes. For an accessible single window, manual hardware is cheaper and simpler to service." },
    ],
  },
  "furniture-sourcing": {
    what: "Furniture sourcing is procurement-led design — a designer selects, specifies and buys furniture, rugs, lighting and accessories from retail and trade-only vendors on your behalf, without a full design package.",
    benefits: [
      "Access to trade-only vendors that don't sell direct to the public",
      "Pieces scaled to your plan rather than to a showroom floor",
      "Orders, freight, damage claims and returns handled for you",
      "Consistent quality standards across a whole room or house",
    ],
    considerations: [
      "Cost-plus, flat fee and commission models differ a lot — get it in writing",
      "Custom upholstery is generally non-returnable once in production",
      "Freight, white-glove delivery and storage are extra line items",
      "Backorders are common — approve a substitution policy in advance",
    ],
    process: "Budget allocation across the room, curated selections with alternates, approval, purchase-order issuance, order tracking and freight coordination, receiving inspection, then delivery and placement.",
    avgCost: "Typically billed as cost-plus at 10–35% over trade pricing, or a flat procurement fee. Furnishing a single room commonly runs $8k–$50k depending on quality tier.",
    candidate: "People who know what they like but don't want to manage twenty vendors, and anyone who has already had a layout drawn and just needs it bought well.",
    faqs: [
      { q: "Do I save money buying through a designer?", a: "Sometimes — trade pricing can offset the fee — but the real saving is avoiding wrong-size, wrong-quality purchases you can't return." },
      { q: "Who handles damaged deliveries?", a: "The designer or their receiving warehouse inspects before delivery and files freight claims. This is one of the main practical reasons to use procurement." },
      { q: "Can I mix my existing furniture in?", a: "Yes, and most designers prefer it. Tell them which pieces are staying at the very start so the plan is built around them." },
    ],
  },
  "color-consultation": {
    what: "A colour consultation resolves paint, stain and finish colours for a room or a whole house — testing samples in your actual light, and producing a written schedule of colours, sheens and where each one goes.",
    benefits: [
      "Colours tested in your own daylight rather than a showroom",
      "A whole-house palette that flows between connected rooms",
      "Sheen and finish specified per surface, not just colour",
      "A written schedule your painter can price and follow",
    ],
    considerations: [
      "North and south-facing rooms shift the same colour dramatically",
      "LED bulbs change how colours read at night — test both",
      "Undertones matter more than the name on the chip",
      "Paint on large sample boards, never small patches on a busy wall",
    ],
    process: "Light and orientation review, sample painting and revisit at different times of day, palette confirmation, then a written colour and sheen schedule per room and surface.",
    avgCost: "Consultations commonly run $300–$1,200 for a single visit, or hourly at $100–$250. Whole-house palettes typically run $800–$2,500.",
    candidate: "Anyone about to paint, sellers preparing a listing, and people who've bought four sample pots and still can't decide.",
    faqs: [
      { q: "How many colours should a house use?", a: "Most whole-house palettes use a small core — one or two wall neutrals, a trim colour, a ceiling white — with accent colours reserved for a few rooms." },
      { q: "What sheen should walls be?", a: "Matte or eggshell on walls, satin or semi-gloss on trim and doors, and a scrubbable finish in kitchens and bathrooms." },
      { q: "Can a colour consultation be done remotely?", a: "Partly. Many designers work from photos plus mailed samples, but for tricky light a site visit gives a far more reliable result." },
    ],
  },
  "renovation-management": {
    what: "Renovation management puts the designer in charge of the build phase — construction drawings, contractor bidding, site visits, schedule tracking, change-order review, and the final punch list.",
    benefits: [
      "One person accountable across trades, vendors and schedule",
      "Bids compared like-for-like rather than on headline price",
      "Site decisions made against the drawings, not improvised",
      "Change orders reviewed before you're asked to sign",
    ],
    considerations: [
      "This is separate from general contracting — the builder still builds",
      "Fees are ongoing across the build, so schedule slippage costs money",
      "Contingency of 10–20% on construction is normal and should be planned",
      "Clarify who holds contracts with subcontractors and vendors",
    ],
    process: "Construction documentation, contractor bid comparison, pre-construction meeting, weekly site visits and reports, submittal and change-order review, then substantial completion, punch list and closeout.",
    avgCost: "Typically billed hourly or as 10–20% of construction cost.",
    candidate: "Anyone renovating remotely, working through a large scope, or who has neither the time nor the appetite to field daily site questions.",
    faqs: [
      { q: "Is a design manager the same as a general contractor?", a: "No. The contractor is responsible for building the work; the designer protects your interests, checks the work against the drawings and manages decisions." },
      { q: "Can my designer hire the contractor for me?", a: "Usually you hold the construction contract directly. The designer runs the bid, recommends, and administers the contract on your behalf." },
      { q: "How often are site visits?", a: "Weekly is standard on an active build, with extra visits at key milestones such as rough-in, tile layout and cabinetry install." },
    ],
  },
  "primary-suite": {
    what: "Primary suite design treats the bedroom, closet and bathroom as one connected space — flow between them, storage split, lighting that works at 6am and 11pm, and a consistent material story across all three.",
    benefits: [
      "Bedroom, bath and closet resolved as one project rather than three",
      "Storage allocated to real wardrobe volume, not guesswork",
      "Sound and light separation between sleeping and bathing zones",
      "A single palette carried across the whole suite",
    ],
    considerations: [
      "Moving the bathroom often means relocating plumbing stacks",
      "Door swings and dressing routes need testing on plan",
      "Ensuite ventilation must be sized correctly or moisture reaches the bedroom",
      "Suite projects are frequently the longest-lead part of a renovation",
    ],
    process: "Routine and storage interview, three-zone layout study, plumbing and lighting coordination, finish and joinery specification, then construction administration, furnishing and styling.",
    avgCost: "Design fees typically run $8k–$25k for the full suite. Construction and furnishing commonly land at $60k–$250k depending on whether the bathroom moves.",
    candidate: "Homeowners renovating a dated primary suite, and anyone whose bedroom, closet and bathroom feel like three unrelated rooms.",
    faqs: [
      { q: "Should the closet be walk-through or separate?", a: "Walk-through closets to the bathroom suit couples on the same schedule; separate entries suit different wake times. It's a lifestyle decision made at plan stage." },
      { q: "Can a primary suite be done in phases?", a: "The bedroom can be furnished first, but bathroom and closet construction should be done together — they usually share walls, plumbing and ventilation." },
      { q: "How much closet space is enough?", a: "Designers inventory what you own — hanging length, shoes, folded volume — and size the closet from that rather than a rule of thumb." },
    ],
  },
  "kids-nursery": {
    what: "Kids and nursery design plans rooms that change as the child does — safe furniture and anchoring, storage at kid height, blackout and sleep support, hard-wearing surfaces, and a scheme that survives the next age bracket.",
    benefits: [
      "Safety detail — anchoring, cord-free blinds, rounded edges — specified up front",
      "Storage scaled to a child's reach so tidying is realistic",
      "Sleep-friendly light control and a calm palette",
      "Choices that adapt from cot to bed to desk without a full redo",
    ],
    considerations: [
      "All tall furniture must be anchored to the wall — non-negotiable",
      "Only cordless window treatments belong in a child's room",
      "Low-VOC paint and finishes matter more here than anywhere else",
      "Themes date fast; put the theme in textiles and art, not joinery",
    ],
    process: "Age and routine interview, layout with growth stages mapped, safety and materials specification, storage and joinery plan, then install and safety check.",
    avgCost: "Design fees typically run $2k–$6k per room, with furnishings commonly $4k–$20k depending on how much joinery is custom.",
    candidate: "Expecting parents, families moving a child from cot to bed, and anyone converting a spare room into a shared kids' space.",
    faqs: [
      { q: "How do I design a nursery that lasts?", a: "Keep the permanent layer neutral and well-made — cot-to-bed conversion, real storage, blackout — and put personality into removable art, bedding and rugs." },
      { q: "What flooring works best in kids' rooms?", a: "Sealed hard flooring with a washable rug beats fitted carpet for spills, allergies and repainting." },
      { q: "Can two children share a room comfortably?", a: "Yes with a planned layout — bunk or parallel beds, separate storage zones and individual reading lights are what make shared rooms work." },
    ],
  },
  "remodel-consulting": {
    what: "Kitchen and bath remodel consulting is advisory rather than full-service — a designer reviews your plans, selections and contractor quotes, flags problems, and gives you a decision list you can execute yourself.",
    benefits: [
      "An expert second opinion before you commit money",
      "Layout and specification errors caught while they're still cheap",
      "Quotes and scope compared with an experienced eye",
      "A prioritised decision list so you know what to settle first",
    ],
    considerations: [
      "Consulting doesn't include drawings, ordering or site supervision",
      "The advice is only as good as the information you supply",
      "You remain responsible for decisions and contractor management",
      "Book before ordering, not after — advice can't undo a purchase",
    ],
    process: "Share plans, quotes and selections, then a one to three hour review session, followed by written notes covering layout risks, specification gaps, sequencing and budget priorities.",
    avgCost: "Commonly $150–$300 per hour or a $500–$2,000 flat review package.",
    candidate: "Confident homeowners running their own remodel who want professional eyes on the plan before the money leaves.",
    faqs: [
      { q: "How is consulting different from full design?", a: "You keep control and do the work. The designer contributes judgement — layout, specification, sequencing and cost sanity-checks — without producing a full package." },
      { q: "When is the best time to book a consult?", a: "Before you sign a contractor and before appliances or cabinetry are ordered. That's when advice can still change the outcome." },
      { q: "Can consulting turn into full service later?", a: "Often yes, and many studios credit part of the consult fee against a subsequent design engagement." },
    ],
  },
  "closet-storage": {
    what: "Closet and storage design plans wardrobes, pantries, mudrooms, garages and utility storage around an inventory of what you actually own — hanging, folding, shoes, bulk items and seasonal overflow.",
    benefits: [
      "Storage sized from a real inventory rather than a standard kit",
      "Hanging, folding and shoe zones proportioned to your wardrobe",
      "Interior lighting so you can see what's in there",
      "Awkward depths, slopes and corners put to work",
    ],
    considerations: [
      "Systems, semi-custom and full custom differ hugely in cost and flexibility",
      "Reach-in closets often need the door type changed to work well",
      "Drawers cost more than shelves — allocate them where they earn it",
      "Ventilation matters in humid climates and enclosed pantries",
    ],
    process: "Inventory count and habits interview, elevation-based layout, fitting and finish selection, fabrication or system order, then installation and loading-in guidance.",
    avgCost: "Design fees typically run $800–$4,000. Installed systems commonly run $1.5k–$8k for a reach-in closet and $8k–$40k for a fitted walk-in.",
    candidate: "Anyone out of storage, households with entryway chaos, and homeowners preparing a home for sale where storage is a selling point.",
    faqs: [
      { q: "Is a custom closet worth it over a stock system?", a: "In irregular or tall spaces, yes — custom recovers dead height and depth. In a plain rectangular reach-in, a well-planned stock system delivers most of the value." },
      { q: "How much hanging space do I need?", a: "Designers measure your existing hanging in linear feet and add roughly 20% for growth, then split between long and double-hang." },
      { q: "Do closets need lighting?", a: "Yes — colour-accurate light inside a wardrobe changes how usable it is. LED strips or sensor-activated fixtures are standard in fitted closets." },
    ],
  },
  "media-theatre": {
    what: "Media and home theatre design covers dedicated cinema rooms and living-room media walls — seating sightlines, screen sizing, acoustic treatment, light control, equipment ventilation and hidden cable routing.",
    benefits: [
      "Screen size and seating distance calculated, not guessed",
      "Acoustic treatment that makes dialogue intelligible",
      "Equipment ventilated and accessible for service",
      "Cables, speakers and controls concealed in the joinery",
    ],
    considerations: [
      "AV integrator and designer must coordinate before wiring",
      "Equipment racks generate heat and need real ventilation",
      "Soundproofing between rooms is structural, not decorative",
      "Reflective surfaces and glossy paint hurt both picture and sound",
    ],
    process: "Use and equipment brief, sightline and seating study, acoustic and light-control plan, joinery and finish specification, AV coordination drawings, then install and calibration alongside the integrator.",
    avgCost: "Design fees typically run $3k–$15k. A dedicated theatre commonly runs $30k–$150k+ including equipment; a designed media wall in a living room often lands at $8k–$40k.",
    candidate: "Households building out a basement or bonus room, and anyone whose living-room TV wall is currently a tangle of cables and mismatched furniture.",
    faqs: [
      { q: "How big should the screen be?", a: "It follows viewing distance and seating rows rather than the biggest panel that fits — your designer and AV integrator size it together." },
      { q: "Do I need acoustic panels?", a: "In a dedicated theatre, yes. In a multipurpose living room, soft furnishings, rugs and lined curtains do much of the same work less visibly." },
      { q: "Can a media room double as a family room?", a: "Yes, with light control and flexible seating. Dedicated cinema rooms optimise for one thing; multipurpose rooms trade some performance for daily usefulness." },
    ],
  },
  "basement-finishing": {
    what: "Basement finishing turns unfinished lower levels into usable rooms — moisture and insulation strategy, ceiling height management, egress and code compliance, lighting for spaces without daylight, and layout for guest, gym, media or rental use.",
    benefits: [
      "Moisture and vapour handled before any finish goes in",
      "Layouts that clear ducts, beams and low headroom",
      "Lighting designed to compensate for little or no daylight",
      "Significant added living area at a lower cost per square foot",
    ],
    considerations: [
      "Bedrooms below grade require code-compliant egress windows",
      "Ceiling height, ducts and beams dictate what's possible",
      "Sump, drainage and radon should be resolved before finishing",
      "Flooring must tolerate slab moisture — some products cannot",
    ],
    process: "Moisture and structure assessment, program and layout options, code and egress review, mechanical coordination, finish and lighting specification, then construction administration and fit-out.",
    avgCost: "Design fees typically run $3k–$12k. Finishing commonly runs $50–$150 per square foot depending on whether bathrooms, egress work or drainage are included.",
    candidate: "Homeowners who need more space without an addition — a guest suite, gym, media room, home office, or an income unit where zoning permits.",
    faqs: [
      { q: "Can a basement bedroom be legal?", a: "Only with compliant egress and ceiling height. Your designer checks local code before the layout is fixed — this is the most common basement compliance failure." },
      { q: "What flooring works below grade?", a: "Moisture-tolerant systems — tile, quality LVP with the right underlayment, or engineered products rated for slab. Solid hardwood is generally a poor choice." },
      { q: "How do I make a basement feel less like one?", a: "Higher light levels with layered warm lighting, taller door and trim proportions, light-toned finishes, and any daylight you can add via enlarged wells." },
    ],
  },
  "adu-small-space": {
    what: "ADU and small-space design covers accessory dwelling units, studios, tiny apartments and guest suites — fitting a full living program into a very small footprint with multi-use furniture and dense, well-detailed storage.",
    benefits: [
      "Every square foot given a purpose",
      "Multi-function furniture specified rather than improvised",
      "Compact kitchen and bath layouts that still meet code",
      "Rental-ready durability where the unit will be let out",
    ],
    considerations: [
      "ADU rules, setbacks and parking requirements vary by city",
      "Compact appliances have different clearances and utility needs",
      "Storage must be designed vertically to keep floor area free",
      "Sound separation matters when the unit adjoins the main house",
    ],
    process: "Program and zoning review, tight-tolerance space plan, compact appliance and fixture specification, joinery-led storage design, then construction coordination and furnishing.",
    avgCost: "Design fees typically run $4k–$15k. ADU construction commonly runs $150–$400 per square foot depending on city and whether it is a conversion or new build.",
    candidate: "Homeowners adding a rental or family unit, city dwellers in small apartments, and anyone converting a garage or basement into an independent living space.",
    faqs: [
      { q: "Do I need permits for an ADU?", a: "Almost always, and rules differ sharply by city and state. Confirm zoning feasibility before spending on design." },
      { q: "How small can a functional unit be?", a: "Many jurisdictions permit studios in the 250–400 sq ft range. Below that, code minimums for kitchen and bath clearances become the binding constraint." },
      { q: "What makes small-space design different?", a: "Tolerances. In a small unit, a few inches decide whether a door swings, a bed fits or a kitchen passes inspection — so everything is drawn, not eyeballed." },
    ],
  },
  "art-curation": {
    what: "Art curation and framing builds a collection for a home or workplace — sourcing original work, prints and photography, planning gallery walls, and specifying framing, hanging heights and lighting.",
    benefits: [
      "A collection with a point of view rather than filler canvases",
      "Access to galleries, art advisors and emerging artists",
      "Framing specified to protect and flatter each piece",
      "Hanging heights, spacing and lighting planned before nails go in",
    ],
    considerations: [
      "UV exposure fades works on paper — glazing and placement matter",
      "Heavy pieces need proper anchoring, sometimes blocking in the wall",
      "Original art has long lead times, especially commissions",
      "Humidity swings damage paper and canvas — avoid bathroom walls",
    ],
    process: "Taste and budget conversation, wall-by-wall art plan, sourcing and shortlisting, framing specification, then professional hanging and accent lighting.",
    avgCost: "Curation is typically billed hourly at $125–$300 or as a percentage of the acquisition budget. Framing commonly runs $200–$1,200 per piece depending on size and conservation glazing.",
    candidate: "People finishing a renovation with bare walls, collectors who want their pieces properly placed, and businesses building a lobby or office collection.",
    faqs: [
      { q: "How high should art hang?", a: "Centre at roughly 57–60 inches from the floor in most rooms, adjusted down over furniture so the piece relates to the sofa or console rather than floating." },
      { q: "Is original art always better than prints?", a: "Not necessarily. A well-framed limited print or photograph often outperforms an expensive but unloved original. Budget is better spent on framing quality than on canvas size." },
      { q: "How do I light art at home?", a: "Adjustable accent fixtures or picture lights with high colour rendering, aimed at about 30 degrees to reduce glare — planned before ceilings are closed where possible." },
    ],
  },
  "textiles-soft-furnishing": {
    what: "Textile and soft furnishing design specifies the fabric layer of a home — upholstery, cushions, bedding, throws, drapery fabric and trims — chosen for durability, hand-feel and how the colours read together.",
    benefits: [
      "Fabrics rated for their actual use — rub counts, cleaning codes, UV",
      "A layered palette of pattern, texture and plain that holds together",
      "Custom cushions, bedding and upholstery made to size",
      "Rooms that feel finished rather than furnished",
    ],
    considerations: [
      "Cleaning codes matter — some fabrics cannot be water-cleaned",
      "Pattern repeats increase yardage and therefore cost",
      "Sun-facing rooms fade natural fibres faster than solution-dyed ones",
      "Workroom lead times commonly run 4–10 weeks after fabric arrives",
    ],
    process: "Use and durability review, fabric shortlisting with memo samples viewed in your light, yardage calculation, workroom fabrication, then delivery and styling.",
    avgCost: "Often part of a wider design fee, or billed hourly. Custom cushions typically run $150–$500 each, reupholstery $900–$4,000 per seat piece including fabric.",
    candidate: "Anyone with good furniture and flat-feeling rooms, households replacing worn upholstery, and clients who want a seasonal textile refresh rather than new furniture.",
    faqs: [
      { q: "Are performance fabrics worth it?", a: "In homes with children, pets or heavy use, yes. Modern performance weaves no longer feel plasticky and can be cleaned without specialist treatment." },
      { q: "How many patterns can one room take?", a: "A common approach is one large pattern, one mid-scale and one small or textural, unified by a shared colour — but the discipline is in the palette, not the count." },
      { q: "Is reupholstering cheaper than buying new?", a: "Only when the frame is good. Reupholstering a well-made hardwood-frame sofa is usually worth it; a flat-pack frame rarely is." },
    ],
  },
  "cabinetry-joinery": {
    what: "Cabinetry and joinery specification is the technical documentation layer — cabinet elevations, door styles and construction, hinge and drawer hardware, interior fittings, and the schedules a fabricator prices and builds from.",
    benefits: [
      "Bids compared on identical specifications, not vague descriptions",
      "Hardware and interior fittings chosen deliberately",
      "Construction grade — frameless, framed, plywood, MDF — specified up front",
      "Shop drawings checked before anything is cut",
    ],
    considerations: [
      "Fabricators price to the spec; vagueness always costs you later",
      "Soft-close hardware quality varies enormously between brands",
      "Painted MDF and painted timber move and age differently",
      "Appliance and sink models must be confirmed before fabrication",
    ],
    process: "Requirement and storage review, cabinet elevations and schedules, hardware and interior fitting specification, fabricator bidding, shop drawing review, then site measure and install inspection.",
    avgCost: "Specification work is commonly billed hourly at $100–$250 or as a flat $2k–$10k package. Cabinetry itself typically runs $500–$1,500 per linear foot depending on grade.",
    candidate: "Anyone bidding cabinetry out to multiple fabricators, and clients who want to control quality rather than accept whatever a showroom package includes.",
    faqs: [
      { q: "Framed or frameless cabinets?", a: "Frameless gives more interior access and a contemporary look; framed suits traditional detailing and offers more forgiving installation on old walls." },
      { q: "What's worth paying up for?", a: "Box construction, hinges and drawer runners. Door style and colour can be changed later; a poor carcass and cheap hardware cannot." },
      { q: "Do I need shop drawings?", a: "Yes for anything custom. They're where discrepancies between design intent and fabrication reality surface — while corrections are still free." },
    ],
  },
  "flooring-tile": {
    what: "Flooring and tile selection specifies hard surfaces throughout a project — wood, tile, stone, and resilient flooring — matched to each room's traffic, moisture and subfloor, with transitions, layouts and grout detailed.",
    benefits: [
      "Materials matched to moisture, traffic and subfloor conditions",
      "Tile layouts drawn so cuts and grout lines land deliberately",
      "Consistent flow and clean transitions between rooms",
      "Slip resistance and maintenance considered, not just appearance",
    ],
    considerations: [
      "Subfloor flatness and moisture testing come before any purchase",
      "Order 10–15% overage for cuts, breakage and future repairs",
      "Natural stone needs sealing and periodic maintenance",
      "Underfloor heating changes the wood species and system you can use",
    ],
    process: "Subfloor and moisture assessment, material shortlisting with full-size samples, layout and transition drawings, grout and trim specification, then install supervision at the layout stage.",
    avgCost: "Specification is usually part of a design fee or billed hourly. Installed costs commonly run $8–$25/sq ft for quality wood or tile, considerably more for stone and intricate patterns.",
    candidate: "Anyone re-flooring more than one room, tackling a wet area, or trying to make new flooring meet an existing floor cleanly.",
    faqs: [
      { q: "Should flooring run the same throughout?", a: "One continuous floor makes a home read larger and simplifies transitions; wet rooms are the usual and sensible exception." },
      { q: "Engineered or solid hardwood?", a: "Engineered is more stable over concrete, radiant heat and humidity swings; solid can be sanded more times. Site conditions usually decide." },
      { q: "What grout colour should I choose?", a: "Matching grout makes the surface read as one plane; contrasting grout emphasises the pattern. Very light grout in floors and showers needs realistic maintenance expectations." },
    ],
  },
  "wallpaper-wall-treatments": {
    what: "Wallpaper and wall treatment design covers papered walls, murals, limewash and plaster finishes, panelling, tadelakt and specialist paint effects — specified with the right substrate prep and installer.",
    benefits: [
      "Character and depth that flat paint can't produce",
      "Substrate preparation specified so the finish lasts",
      "Pattern scale and repeat matched to the room's proportions",
      "Specialist installers sourced and coordinated",
    ],
    considerations: [
      "Wall prep and lining often cost as much as the material",
      "Repeat and match affect roll quantity significantly",
      "Some plaster and limewash finishes are difficult to patch invisibly",
      "Grasscloth and natural papers can shade-vary between rolls",
    ],
    process: "Wall condition survey, material and pattern selection with large samples, quantity take-off including repeat, installer sourcing and scheduling, then supervision of prep and hang.",
    avgCost: "Specification is typically part of a design fee. Materials commonly run $50–$400 per roll, with installation at $50–$120 per roll; artisan plaster finishes often run $12–$30/sq ft installed.",
    candidate: "People with a flat, characterless room, powder rooms and entries that can take a bold move, and homes where architecture needs emphasising.",
    faqs: [
      { q: "Where is wallpaper a bad idea?", a: "Unventilated bathrooms and steam-heavy spaces, unless you use a vinyl or specifically rated product with correct ventilation." },
      { q: "Is limewash better than paint?", a: "Different, not better — limewash gives depth and movement, but it's harder to touch up and needs a compatible substrate." },
      { q: "How much extra material should I order?", a: "Enough for the pattern repeat plus 10–15%. Dye lots change, so ordering more later rarely matches." },
    ],
  },
  "sustainable-design": {
    what: "Sustainable and eco design prioritises indoor air quality, low-embodied-carbon and durable materials, energy-efficient lighting and appliances, reuse and reupholstery over replacement, and honest sourcing rather than green marketing.",
    benefits: [
      "Low-VOC finishes and better indoor air quality",
      "Durable materials that don't need replacing in five years",
      "Reuse and restoration of pieces you already own",
      "Certified sourcing rather than unverified claims",
    ],
    considerations: [
      "\"Eco\" is unregulated — look for FSC, GREENGUARD, Cradle to Cradle or similar",
      "Vintage and reclaimed pieces have unpredictable lead times",
      "Some sustainable materials cost more up front and pay back over time",
      "Shipping distance is part of the footprint — local sourcing matters",
    ],
    process: "Priority-setting conversation, audit of what can be kept or restored, certified material and finish selection, energy and lighting review, then procurement weighted to local and reclaimed sources.",
    avgCost: "Fees match conventional design work. Material budgets are often 5–20% higher up front, with savings arriving through longevity, energy use and fewer replacements.",
    candidate: "Households sensitive to indoor air quality, clients who want to buy less and better, and anyone renovating who'd rather restore than landfill.",
    faqs: [
      { q: "Which certifications actually mean something?", a: "FSC for timber, GREENGUARD Gold for emissions, OEKO-TEX for textiles and Cradle to Cradle for whole-product assessment are the most reliable signals." },
      { q: "Is sustainable design more expensive?", a: "Often slightly higher up front and cheaper over the life of the room, because durable pieces and restored furniture aren't replaced on a five-year cycle." },
      { q: "What's the single biggest sustainability win?", a: "Keeping and restoring what you already own. No new product beats a reupholstered sofa on footprint." },
    ],
  },
  "accessible-design": {
    what: "Ageing-in-place and accessible design adapts homes for mobility, sight and balance changes — level thresholds, circulation widths, reinforced grab bar blocking, reachable storage, and lighting and contrast that support failing vision.",
    benefits: [
      "Homes that stay usable as needs change",
      "Bathroom safety solved without an institutional look",
      "Wider routes, level entries and reachable controls",
      "Contrast and lighting that reduce fall risk",
    ],
    considerations: [
      "Grab bars need in-wall blocking — plan before drywall closes",
      "Curbless showers require attention to floor structure and drainage",
      "Flooring transitions and high-pile rugs are common trip hazards",
      "Some adaptations may qualify for insurance or programme support — check locally",
    ],
    process: "Needs and mobility assessment, sometimes with an occupational therapist, circulation and clearance review, adaptation plan by priority, specification of fixtures and hardware, then construction coordination.",
    avgCost: "Design fees typically run $2k–$10k. Individual adaptations range from a few hundred dollars for hardware and lighting to $20k–$60k for a fully accessible bathroom.",
    candidate: "Homeowners planning to stay in place, families adapting a home for a parent, and anyone recovering from injury or living with reduced mobility.",
    faqs: [
      { q: "Does accessible design have to look clinical?", a: "No. Modern grab bars, curbless showers, lever hardware and good lighting read as contemporary design when they're specified deliberately." },
      { q: "What should I do first?", a: "Usually the bathroom and the entry — the two highest-risk areas — followed by lighting levels and removing threshold trip hazards." },
      { q: "Can adaptations be planned before they're needed?", a: "Yes, and it's much cheaper. Blocking in walls, wider door openings and level entries cost little during a renovation and a great deal to retrofit." },
    ],
  },
  "wellness-feng-shui": {
    what: "Feng shui and wellness design arranges homes around comfort, calm and daily routine — furniture placement and sightlines, daylight and circadian lighting, air quality and greenery, clutter reduction and clearly defined rest zones.",
    benefits: [
      "Furniture placed so rooms feel settled rather than exposed",
      "Daylight and evening lighting supporting sleep patterns",
      "Air quality, plants and natural materials brought into the plan",
      "Defined zones for rest, work and gathering in shared homes",
    ],
    considerations: [
      "Feng shui schools differ — agree which approach the designer uses",
      "Wellness claims should be treated as comfort, not medical advice",
      "Some recommendations conflict with the existing architecture",
      "The strongest results usually come from decluttering, not purchasing",
    ],
    process: "Home walkthrough and routine interview, plan analysis, placement and layout recommendations, lighting, material and greenery specification, then a phased implementation list.",
    avgCost: "Consultations commonly run $300–$1,500; full room implementation is billed like standard design work, hourly or flat fee.",
    candidate: "People who find their home unsettling but can't say why, households in transition, and anyone prioritising calm and sleep quality over aesthetics alone.",
    faqs: [
      { q: "Is feng shui compatible with modern interiors?", a: "Yes. Most of its practical guidance — command position for beds and desks, clear circulation, balanced light — is ordinary good space planning." },
      { q: "What is the 'command position'?", a: "Placing a bed or desk so you can see the door without being directly in line with it. It's the most commonly applied principle and costs nothing to try." },
      { q: "Do I need to buy specific objects?", a: "No. A good consultant works with what you own and focuses on placement, light and editing before recommending purchases." },
    ],
  },
  "model-home-multifamily": {
    what: "Model home and multi-family design creates the schemes that sell or lease a development — merchandised model units, amenity and lobby spaces, and repeatable finish packages applied across many units.",
    benefits: [
      "Model units merchandised to a target buyer or renter profile",
      "Finish packages that price predictably at volume",
      "Amenity spaces that support the marketing story",
      "Documentation that scales across dozens or hundreds of units",
    ],
    considerations: [
      "Volume purchasing and lead times drive scheduling decisions",
      "Durability and turnover cost matter more than in single-family work",
      "Budgets are per-unit and unforgiving of bespoke selections",
      "Sales or leasing deadlines dominate the programme",
    ],
    process: "Target-market and pro-forma review, finish package options at defined price points, model unit merchandising plan, amenity space design, volume procurement, then staged install ahead of sales launch.",
    avgCost: "Typically quoted per model unit or per package — model merchandising commonly runs $25k–$120k per unit including furnishings, with finish package design fees quoted separately.",
    candidate: "Developers, builders and multi-family owners launching sales or repositioning an existing property.",
    faqs: [
      { q: "How is model home design different from residential?", a: "It sells a lifestyle to a market segment rather than serving one client, and it must hit a per-unit budget that survives being repeated." },
      { q: "Do model furnishings stay with the unit?", a: "Sometimes. Packages are commonly rented for the sales period, then sold with the unit or redeployed — decide early, since it changes procurement." },
      { q: "How many finish packages should we offer?", a: "Two or three usually maximises appeal without creating a construction and procurement headache." },
    ],
  },
  "restaurant-bar": {
    what: "Restaurant and bar design covers front and back of house — seat count and circulation, bar and service station layout, acoustics, lighting for food and mood, durable finishes, and coordination with kitchen consultants and code officials.",
    benefits: [
      "Seat count balanced against comfort and service flow",
      "Bar and service stations laid out around real workflow",
      "Acoustics controlled so guests can hold a conversation",
      "Lighting that flatters food, guests and the room at night",
    ],
    considerations: [
      "Health department, occupancy and egress rules shape the plan",
      "Grease, moisture and constant cleaning limit finish choices",
      "Kitchen ventilation and make-up air affect the whole layout",
      "Every seat removed for comfort has a direct revenue cost",
    ],
    process: "Concept and menu-driven programming, seating and flow test fits, kitchen consultant coordination, material and lighting design, permit documentation, then site administration through opening.",
    avgCost: "Design fees are commonly quoted flat or per square foot; independent restaurant projects often start around $20k in fees, with build costs typically $200–$600/sq ft.",
    candidate: "Independent restaurateurs, bar operators and hospitality groups opening, relocating or refreshing a venue.",
    faqs: [
      { q: "How much space per seat should we plan?", a: "Roughly 15–20 sq ft per seat in the dining area depending on service style, before back of house and circulation are added." },
      { q: "How do we stop the room being too loud?", a: "Acoustic ceiling treatment, upholstered banquettes, soft wall panels and broken sightlines. It has to be designed in — you can't fix it after opening cheaply." },
      { q: "Who handles the kitchen design?", a: "A foodservice consultant typically designs the kitchen; the interior designer coordinates it with the front of house, finishes and code documentation." },
    ],
  },
  "healthcare-interiors": {
    what: "Healthcare and wellness interiors cover clinics, dental and medical practices, therapy rooms, spas and studios — patient flow and privacy, infection-control-appropriate surfaces, equipment clearances, accessibility, and a calming environment.",
    benefits: [
      "Patient journey and privacy planned from arrival to treatment",
      "Cleanable, non-porous surfaces specified correctly",
      "Equipment clearances and staff workflow coordinated",
      "Waiting areas that reduce anxiety rather than amplify it",
    ],
    considerations: [
      "Regulatory and accessibility requirements are strict and jurisdictional",
      "Privacy rules affect sightlines, acoustics and reception design",
      "Some finishes and joinery must meet infection-control standards",
      "Medical equipment has power, weight and clearance requirements",
    ],
    process: "Clinical workflow and compliance review, patient-flow layout, equipment and clearance coordination, compliant finish and lighting specification, permit documentation, then install and commissioning.",
    avgCost: "Fees are usually per square foot or flat by phase; small clinic fit-outs commonly run $30k–$120k in construction plus separate design fees, varying sharply by specialty.",
    candidate: "Practice owners opening or relocating, and existing clinics whose layout no longer fits patient volume or new equipment.",
    faqs: [
      { q: "What makes healthcare interiors different?", a: "Compliance and workflow lead. Cleanability, privacy, accessibility and equipment clearances decide the plan; aesthetics work inside those constraints." },
      { q: "Do we need a licensed professional?", a: "Usually yes for permit drawings — an architect or registered interior designer, depending on state and scope." },
      { q: "Can a clinic feel less clinical?", a: "Yes — warm lighting, natural materials in non-clinical zones, acoustic control and good wayfinding change the experience without breaking compliance." },
    ],
  },
  "short-term-rental-styling": {
    what: "Vacation and short-term rental styling designs income properties for guests and for the camera — durable, replaceable furnishings, photogenic focal points, complete guest amenities, and layouts that maximise legal sleeping capacity.",
    benefits: [
      "Listing photography that competes in a crowded market",
      "Furniture chosen for turnover, cleaning and replacement cost",
      "Sleeping capacity maximised within safety and legal limits",
      "A consistent amenity standard that lifts review scores",
    ],
    considerations: [
      "Local short-term rental rules and caps change frequently",
      "Buy for replaceability — everything in a rental has a finite life",
      "Bedding, towels and kitchen kit need duplicate stock for turnovers",
      "Guest safety items are mandatory in most jurisdictions",
    ],
    process: "Market and comp-set review, layout and sleeping-capacity plan, durable furnishings and amenity specification, bulk procurement, install and staging, then a photography day.",
    avgCost: "Design fees commonly run $2k–$8k. Furnishing a one to two bedroom rental typically runs $12k–$40k including amenities and linens.",
    candidate: "Owners launching a short-term rental, hosts whose listing underperforms local comps, and investors furnishing multiple units to one standard.",
    faqs: [
      { q: "What furniture holds up in a short-term rental?", a: "Solid-frame seating with removable washable covers, laminate or sealed surfaces, and mid-tier pieces you can replace without pain — not fragile designer items." },
      { q: "How much does styling affect bookings?", a: "The listing photos drive click-through, so focal points, light and staging matter directly. Ask your designer to plan for the camera as well as the guest." },
      { q: "What amenities are worth including?", a: "Blackout in every bedroom, strong wifi, a properly equipped kitchen, spare linens and clear guest information — these dominate review comments." },
    ],
  },
  procurement: {
    what: "Procurement and project purchasing is the back-office of a design project — issuing purchase orders, tracking acknowledgements and lead times, managing freight and receiving, inspecting for damage, and scheduling delivery to site.",
    benefits: [
      "One purchase order trail instead of dozens of personal orders",
      "Lead times tracked and expedited before they derail the install",
      "Damaged goods caught at the warehouse, not in your living room",
      "A single consolidated delivery instead of weeks of doorstep chaos",
    ],
    considerations: [
      "Receiving, storage and white-glove delivery are real line items",
      "Custom orders are usually non-cancellable once in production",
      "Freight claims are time-limited — inspection must be prompt",
      "Understand whether the fee is cost-plus, flat or a management percentage",
    ],
    process: "Budget and specification handover, purchase order issuance, acknowledgement and lead-time tracking, freight consolidation to a receiving warehouse, inspection and repair, then scheduled site delivery and install.",
    avgCost: "Commonly 10–25% of the goods value as a procurement or management fee, or a flat fee per project; receiving and storage typically add 3–8%.",
    candidate: "Anyone furnishing a whole home, out-of-town clients, and people who already have a design plan but no appetite for chasing twenty vendors.",
    faqs: [
      { q: "Can I buy the furniture myself to save money?", a: "You can, and for a few pieces it's fine. Across a whole home, the freight claims, backorders and delivery scheduling are what the fee actually buys." },
      { q: "What is a receiving warehouse?", a: "A third-party facility that accepts, unpacks, inspects and stores your items until everything is ready for one coordinated delivery day." },
      { q: "What happens if something arrives damaged?", a: "The receiver documents and files the freight claim, and the designer arranges repair or replacement — usually before you ever see the item." },
    ],
  },
  "3d-rendering": {
    what: "3D rendering and visualisation turns a design into photoreal images, walkthroughs or VR before anything is built — modelling the space with real materials, lighting and furniture specifications.",
    benefits: [
      "See the scheme before committing to spend",
      "Material and colour decisions compared side by side",
      "Buy-in from partners, investors or planning bodies",
      "Errors caught in the model rather than on site",
    ],
    considerations: [
      "Renderings are only as accurate as the measurements behind them",
      "Photoreal images can flatter — check real samples too",
      "Revisions are usually limited per package",
      "Rendering is a deliverable, not a substitute for construction drawings",
    ],
    process: "Plan and specification handover, 3D model build, material and lighting setup, draft grey-scale views for layout approval, then final rendered images or a walkthrough animation.",
    avgCost: "Still images typically run $250–$1,200 per view; animated walkthroughs commonly $1,500–$8,000 depending on length and detail.",
    candidate: "Clients who struggle to read floor plans, developers marketing off-plan, and anyone making an expensive, irreversible material decision.",
    faqs: [
      { q: "How accurate are renderings?", a: "Geometry and scale are usually exact. Colour and material perception can shift with lighting setup, so always confirm against physical samples." },
      { q: "Do I need renderings for a small project?", a: "Rarely for a single room refresh. They earn their cost when construction, custom joinery or off-plan sales are involved." },
      { q: "Can renderings be produced from my architect's drawings?", a: "Yes — most visualisers work directly from CAD or a measured plan set plus a finishes schedule." },
    ],
  },
  "move-in-unpacking": {
    what: "Move-in and unpacking services take a home from boxes to fully functional in days — furniture placement, kitchen and closet organisation, bed making, art hanging and packing-material removal.",
    benefits: [
      "A functional, unpacked home in days rather than months",
      "Kitchens and closets organised systematically from day one",
      "Furniture placed to a plan instead of wherever the movers left it",
      "Boxes and packing waste removed at the end",
    ],
    considerations: [
      "Book alongside the moving date — availability is tight",
      "Decide in advance what gets donated rather than unpacked",
      "Art hanging may need a separate installer for heavy pieces",
      "Some teams charge per organiser-hour, so pre-purging saves money",
    ],
    process: "Pre-move walkthrough and furniture plan, move-day placement direction, systematic unpacking by zone, kitchen and closet organisation, art hanging and styling, then debris removal.",
    avgCost: "Commonly billed per organiser-hour at $60–$150, with full-home move-ins typically landing at $2k–$12k depending on size and volume.",
    candidate: "Busy households, relocating families, downsizers, and anyone moving into a home they've just had designed.",
    faqs: [
      { q: "How long does a full-home unpack take?", a: "A team of three to five typically clears a three-bedroom home in one to three days when the furniture plan is decided in advance." },
      { q: "Should I purge before or after the move?", a: "Before, always. Paying to move and unpack things you'll discard is the single biggest avoidable cost." },
      { q: "Can this be combined with design work?", a: "Yes — many studios pair a move-in service with a furniture plan so pieces land in their designed positions on day one." },
    ],
  },
};

export function getServiceContent(slug: string, name: string): ServiceContent {
  return OVERRIDES[slug] ?? defaultContent(name);
}
