/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as SiteTermsRouteImport } from './routes/_site.terms'
import { Route as SiteSubmitRouteImport } from './routes/_site.submit'
import { Route as SiteSearchRouteImport } from './routes/_site.search'
import { Route as SiteSafetyRouteImport } from './routes/_site.safety'
import { Route as SitePrivacyRouteImport } from './routes/_site.privacy'
import { Route as SiteMatchRouteImport } from './routes/_site.match'
import { Route as SiteLoginRouteImport } from './routes/_site.login'
import { Route as SiteFavoritesRouteImport } from './routes/_site.favorites'
import { Route as SiteDashboardRouteImport } from './routes/_site.dashboard'
import { Route as SiteContactRouteImport } from './routes/_site.contact'
import { Route as SiteBrandsRouteImport } from './routes/_site.brands'
import { Route as SiteAboutRouteImport } from './routes/_site.about'
import { Route as ApiPublicAdminReseedRouteImport } from './routes/api.public.admin-reseed'
import { Route as SiteTxCityRouteImport } from './routes/_site.tx.$city'
import { Route as SiteTreatmentSlugRouteImport } from './routes/_site.treatment.$slug'
import { Route as SiteProviderSlugRouteImport } from './routes/_site.provider.$slug'
import { Route as SiteBrandSlugRouteImport } from './routes/_site.brand.$slug'
import { Route as SiteBestCityRouteImport } from './routes/_site.best.$city'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTermsRoute = SiteTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => SiteRoute,
} as any)
const SiteSubmitRoute = SiteSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => SiteRoute,
} as any)
const SiteSearchRoute = SiteSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => SiteRoute,
} as any)
const SiteSafetyRoute = SiteSafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => SiteRoute,
} as any)
const SitePrivacyRoute = SitePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => SiteRoute,
} as any)
const SiteMatchRoute = SiteMatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => SiteRoute,
} as any)
const SiteLoginRoute = SiteLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => SiteRoute,
} as any)
const SiteFavoritesRoute = SiteFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => SiteRoute,
} as any)
const SiteDashboardRoute = SiteDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRoute,
} as any)
const SiteBrandsRoute = SiteBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRoute,
} as any)
const ApiPublicAdminReseedRoute = ApiPublicAdminReseedRouteImport.update({
  id: '/api/public/admin-reseed',
  path: '/api/public/admin-reseed',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteTxCityRoute = SiteTxCityRouteImport.update({
  id: '/tx/$city',
  path: '/tx/$city',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTreatmentSlugRoute = SiteTreatmentSlugRouteImport.update({
  id: '/treatment/$slug',
  path: '/treatment/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SiteProviderSlugRoute = SiteProviderSlugRouteImport.update({
  id: '/provider/$slug',
  path: '/provider/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SiteBrandSlugRoute = SiteBrandSlugRouteImport.update({
  id: '/brand/$slug',
  path: '/brand/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SiteBestCityRoute = SiteBestCityRouteImport.update({
  id: '/best/$city',
  path: '/best/$city',
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about': typeof SiteAboutRoute
  '/brands': typeof SiteBrandsRoute
  '/contact': typeof SiteContactRoute
  '/dashboard': typeof SiteDashboardRoute
  '/favorites': typeof SiteFavoritesRoute
  '/login': typeof SiteLoginRoute
  '/match': typeof SiteMatchRoute
  '/privacy': typeof SitePrivacyRoute
  '/safety': typeof SiteSafetyRoute
  '/search': typeof SiteSearchRoute
  '/submit': typeof SiteSubmitRoute
  '/terms': typeof SiteTermsRoute
  '/best/$city': typeof SiteBestCityRoute
  '/brand/$slug': typeof SiteBrandSlugRoute
  '/provider/$slug': typeof SiteProviderSlugRoute
  '/treatment/$slug': typeof SiteTreatmentSlugRoute
  '/tx/$city': typeof SiteTxCityRoute
  '/api/public/admin-reseed': typeof ApiPublicAdminReseedRoute
}
export interface FileRoutesByTo {
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about': typeof SiteAboutRoute
  '/brands': typeof SiteBrandsRoute
  '/contact': typeof SiteContactRoute
  '/dashboard': typeof SiteDashboardRoute
  '/favorites': typeof SiteFavoritesRoute
  '/login': typeof SiteLoginRoute
  '/match': typeof SiteMatchRoute
  '/privacy': typeof SitePrivacyRoute
  '/safety': typeof SiteSafetyRoute
  '/search': typeof SiteSearchRoute
  '/submit': typeof SiteSubmitRoute
  '/terms': typeof SiteTermsRoute
  '/': typeof SiteIndexRoute
  '/best/$city': typeof SiteBestCityRoute
  '/brand/$slug': typeof SiteBrandSlugRoute
  '/provider/$slug': typeof SiteProviderSlugRoute
  '/treatment/$slug': typeof SiteTreatmentSlugRoute
  '/tx/$city': typeof SiteTxCityRoute
  '/api/public/admin-reseed': typeof ApiPublicAdminReseedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_site/about': typeof SiteAboutRoute
  '/_site/brands': typeof SiteBrandsRoute
  '/_site/contact': typeof SiteContactRoute
  '/_site/dashboard': typeof SiteDashboardRoute
  '/_site/favorites': typeof SiteFavoritesRoute
  '/_site/login': typeof SiteLoginRoute
  '/_site/match': typeof SiteMatchRoute
  '/_site/privacy': typeof SitePrivacyRoute
  '/_site/safety': typeof SiteSafetyRoute
  '/_site/search': typeof SiteSearchRoute
  '/_site/submit': typeof SiteSubmitRoute
  '/_site/terms': typeof SiteTermsRoute
  '/_site/': typeof SiteIndexRoute
  '/_site/best/$city': typeof SiteBestCityRoute
  '/_site/brand/$slug': typeof SiteBrandSlugRoute
  '/_site/provider/$slug': typeof SiteProviderSlugRoute
  '/_site/treatment/$slug': typeof SiteTreatmentSlugRoute
  '/_site/tx/$city': typeof SiteTxCityRoute
  '/api/public/admin-reseed': typeof ApiPublicAdminReseedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/about'
    | '/brands'
    | '/contact'
    | '/dashboard'
    | '/favorites'
    | '/login'
    | '/match'
    | '/privacy'
    | '/safety'
    | '/search'
    | '/submit'
    | '/terms'
    | '/best/$city'
    | '/brand/$slug'
    | '/provider/$slug'
    | '/treatment/$slug'
    | '/tx/$city'
    | '/api/public/admin-reseed'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sitemap.xml'
    | '/about'
    | '/brands'
    | '/contact'
    | '/dashboard'
    | '/favorites'
    | '/login'
    | '/match'
    | '/privacy'
    | '/safety'
    | '/search'
    | '/submit'
    | '/terms'
    | '/'
    | '/best/$city'
    | '/brand/$slug'
    | '/provider/$slug'
    | '/treatment/$slug'
    | '/tx/$city'
    | '/api/public/admin-reseed'
  id:
    | '__root__'
    | '/_site'
    | '/sitemap.xml'
    | '/_site/about'
    | '/_site/brands'
    | '/_site/contact'
    | '/_site/dashboard'
    | '/_site/favorites'
    | '/_site/login'
    | '/_site/match'
    | '/_site/privacy'
    | '/_site/safety'
    | '/_site/search'
    | '/_site/submit'
    | '/_site/terms'
    | '/_site/'
    | '/_site/best/$city'
    | '/_site/brand/$slug'
    | '/_site/provider/$slug'
    | '/_site/treatment/$slug'
    | '/_site/tx/$city'
    | '/api/public/admin-reseed'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicAdminReseedRoute: typeof ApiPublicAdminReseedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/terms': {
      id: '/_site/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof SiteTermsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/submit': {
      id: '/_site/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SiteSubmitRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/search': {
      id: '/_site/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SiteSearchRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/safety': {
      id: '/_site/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SiteSafetyRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/privacy': {
      id: '/_site/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof SitePrivacyRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/match': {
      id: '/_site/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof SiteMatchRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/login': {
      id: '/_site/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof SiteLoginRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/favorites': {
      id: '/_site/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof SiteFavoritesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/dashboard': {
      id: '/_site/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof SiteDashboardRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/brands': {
      id: '/_site/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof SiteBrandsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRoute
    }
    '/api/public/admin-reseed': {
      id: '/api/public/admin-reseed'
      path: '/api/public/admin-reseed'
      fullPath: '/api/public/admin-reseed'
      preLoaderRoute: typeof ApiPublicAdminReseedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/tx/$city': {
      id: '/_site/tx/$city'
      path: '/tx/$city'
      fullPath: '/tx/$city'
      preLoaderRoute: typeof SiteTxCityRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/treatment/$slug': {
      id: '/_site/treatment/$slug'
      path: '/treatment/$slug'
      fullPath: '/treatment/$slug'
      preLoaderRoute: typeof SiteTreatmentSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/provider/$slug': {
      id: '/_site/provider/$slug'
      path: '/provider/$slug'
      fullPath: '/provider/$slug'
      preLoaderRoute: typeof SiteProviderSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/brand/$slug': {
      id: '/_site/brand/$slug'
      path: '/brand/$slug'
      fullPath: '/brand/$slug'
      preLoaderRoute: typeof SiteBrandSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/best/$city': {
      id: '/_site/best/$city'
      path: '/best/$city'
      fullPath: '/best/$city'
      preLoaderRoute: typeof SiteBestCityRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface SiteRouteChildren {
  SiteAboutRoute: typeof SiteAboutRoute
  SiteBrandsRoute: typeof SiteBrandsRoute
  SiteContactRoute: typeof SiteContactRoute
  SiteDashboardRoute: typeof SiteDashboardRoute
  SiteFavoritesRoute: typeof SiteFavoritesRoute
  SiteLoginRoute: typeof SiteLoginRoute
  SiteMatchRoute: typeof SiteMatchRoute
  SitePrivacyRoute: typeof SitePrivacyRoute
  SiteSafetyRoute: typeof SiteSafetyRoute
  SiteSearchRoute: typeof SiteSearchRoute
  SiteSubmitRoute: typeof SiteSubmitRoute
  SiteTermsRoute: typeof SiteTermsRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SiteBestCityRoute: typeof SiteBestCityRoute
  SiteBrandSlugRoute: typeof SiteBrandSlugRoute
  SiteProviderSlugRoute: typeof SiteProviderSlugRoute
  SiteTreatmentSlugRoute: typeof SiteTreatmentSlugRoute
  SiteTxCityRoute: typeof SiteTxCityRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAboutRoute: SiteAboutRoute,
  SiteBrandsRoute: SiteBrandsRoute,
  SiteContactRoute: SiteContactRoute,
  SiteDashboardRoute: SiteDashboardRoute,
  SiteFavoritesRoute: SiteFavoritesRoute,
  SiteLoginRoute: SiteLoginRoute,
  SiteMatchRoute: SiteMatchRoute,
  SitePrivacyRoute: SitePrivacyRoute,
  SiteSafetyRoute: SiteSafetyRoute,
  SiteSearchRoute: SiteSearchRoute,
  SiteSubmitRoute: SiteSubmitRoute,
  SiteTermsRoute: SiteTermsRoute,
  SiteIndexRoute: SiteIndexRoute,
  SiteBestCityRoute: SiteBestCityRoute,
  SiteBrandSlugRoute: SiteBrandSlugRoute,
  SiteProviderSlugRoute: SiteProviderSlugRoute,
  SiteTreatmentSlugRoute: SiteTreatmentSlugRoute,
  SiteTxCityRoute: SiteTxCityRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicAdminReseedRoute: ApiPublicAdminReseedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
