/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as SiteAboutRouteImport } from './routes/_site.about'
import { Route as SiteAdminRouteImport } from './routes/_site.admin'
import { Route as SiteCompareRouteImport } from './routes/_site.compare'
import { Route as SiteContactRouteImport } from './routes/_site.contact'
import { Route as SiteDashboardRouteImport } from './routes/_site.dashboard'
import { Route as SiteFavoritesRouteImport } from './routes/_site.favorites'
import { Route as SiteForBusinessRouteImport } from './routes/_site.for-business'
import { Route as SiteHowItWorksRouteImport } from './routes/_site.how-it-works'
import { Route as SiteLoginRouteImport } from './routes/_site.login'
import { Route as SiteMatchRouteImport } from './routes/_site.match'
import { Route as SitePrivacyRouteImport } from './routes/_site.privacy'
import { Route as SiteSearchRouteImport } from './routes/_site.search'
import { Route as SiteSubmitRouteImport } from './routes/_site.submit'
import { Route as SiteTermsRouteImport } from './routes/_site.terms'
import { Route as SiteWelcomeRouteImport } from './routes/_site.welcome'
import { Route as SiteAdminArticlesRouteImport } from './routes/_site.admin.articles'
import { Route as SiteClaimIndexRouteImport } from './routes/_site.claim.index'
import { Route as SiteClaimSlugRouteImport } from './routes/_site.claim.$slug'
import { Route as SiteProviderSlugRouteImport } from './routes/_site.provider.$slug'
import { Route as SiteReviewIndexRouteImport } from './routes/_site.review.index'
import { Route as SiteReviewSlugRouteImport } from './routes/_site.review.$slug'
import { Route as SiteServiceSlugRouteImport } from './routes/_site.service.$slug'
import { Route as SiteStyleSlugRouteImport } from './routes/_site.style.$slug'
import { Route as ApiPublicAdminSeedImportRouteImport } from './routes/api.public.admin-seed-import'
import { Route as ApiPublicTrackRouteImport } from './routes/api.public.track'
import { Route as SiteAdminProviderPlaceIdRouteImport } from './routes/_site.admin.provider.$placeId'
import { Route as SiteDashboardListingPlaceIdRouteImport } from './routes/_site.dashboard.listing.$placeId'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAdminRoute = SiteAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCompareRoute = SiteCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRoute,
} as any)
const SiteDashboardRoute = SiteDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => SiteRoute,
} as any)
const SiteFavoritesRoute = SiteFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => SiteRoute,
} as any)
const SiteForBusinessRoute = SiteForBusinessRouteImport.update({
  id: '/for-business',
  path: '/for-business',
  getParentRoute: () => SiteRoute,
} as any)
const SiteHowItWorksRoute = SiteHowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => SiteRoute,
} as any)
const SiteLoginRoute = SiteLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => SiteRoute,
} as any)
const SiteMatchRoute = SiteMatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => SiteRoute,
} as any)
const SitePrivacyRoute = SitePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => SiteRoute,
} as any)
const SiteSearchRoute = SiteSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => SiteRoute,
} as any)
const SiteSubmitRoute = SiteSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTermsRoute = SiteTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => SiteRoute,
} as any)
const SiteWelcomeRoute = SiteWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAdminArticlesRoute = SiteAdminArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => SiteAdminRoute,
} as any)
const SiteClaimIndexRoute = SiteClaimIndexRouteImport.update({
  id: '/claim/',
  path: '/claim/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteClaimSlugRoute = SiteClaimSlugRouteImport.update({
  id: '/claim/$slug',
  path: '/claim/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SiteProviderSlugRoute = SiteProviderSlugRouteImport.update({
  id: '/provider/$slug',
  path: '/provider/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SiteReviewIndexRoute = SiteReviewIndexRouteImport.update({
  id: '/review/',
  path: '/review/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteReviewSlugRoute = SiteReviewSlugRouteImport.update({
  id: '/review/$slug',
  path: '/review/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SiteServiceSlugRoute = SiteServiceSlugRouteImport.update({
  id: '/service/$slug',
  path: '/service/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SiteStyleSlugRoute = SiteStyleSlugRouteImport.update({
  id: '/style/$slug',
  path: '/style/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const ApiPublicAdminSeedImportRoute =
  ApiPublicAdminSeedImportRouteImport.update({
    id: '/api/public/admin-seed-import',
    path: '/api/public/admin-seed-import',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTrackRoute = ApiPublicTrackRouteImport.update({
  id: '/api/public/track',
  path: '/api/public/track',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteAdminProviderPlaceIdRoute =
  SiteAdminProviderPlaceIdRouteImport.update({
    id: '/provider/$placeId',
    path: '/provider/$placeId',
    getParentRoute: () => SiteAdminRoute,
  } as any)
const SiteDashboardListingPlaceIdRoute =
  SiteDashboardListingPlaceIdRouteImport.update({
    id: '/listing/$placeId',
    path: '/listing/$placeId',
    getParentRoute: () => SiteDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about': typeof SiteAboutRoute
  '/admin': typeof SiteAdminRouteWithChildren
  '/compare': typeof SiteCompareRoute
  '/contact': typeof SiteContactRoute
  '/dashboard': typeof SiteDashboardRouteWithChildren
  '/favorites': typeof SiteFavoritesRoute
  '/for-business': typeof SiteForBusinessRoute
  '/how-it-works': typeof SiteHowItWorksRoute
  '/login': typeof SiteLoginRoute
  '/match': typeof SiteMatchRoute
  '/privacy': typeof SitePrivacyRoute
  '/search': typeof SiteSearchRoute
  '/submit': typeof SiteSubmitRoute
  '/terms': typeof SiteTermsRoute
  '/welcome': typeof SiteWelcomeRoute
  '/admin/articles': typeof SiteAdminArticlesRoute
  '/claim/$slug': typeof SiteClaimSlugRoute
  '/provider/$slug': typeof SiteProviderSlugRoute
  '/review/$slug': typeof SiteReviewSlugRoute
  '/service/$slug': typeof SiteServiceSlugRoute
  '/style/$slug': typeof SiteStyleSlugRoute
  '/api/public/admin-seed-import': typeof ApiPublicAdminSeedImportRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/claim/': typeof SiteClaimIndexRoute
  '/review/': typeof SiteReviewIndexRoute
  '/admin/provider/$placeId': typeof SiteAdminProviderPlaceIdRoute
  '/dashboard/listing/$placeId': typeof SiteDashboardListingPlaceIdRoute
}
export interface FileRoutesByTo {
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about': typeof SiteAboutRoute
  '/admin': typeof SiteAdminRouteWithChildren
  '/compare': typeof SiteCompareRoute
  '/contact': typeof SiteContactRoute
  '/dashboard': typeof SiteDashboardRouteWithChildren
  '/favorites': typeof SiteFavoritesRoute
  '/for-business': typeof SiteForBusinessRoute
  '/how-it-works': typeof SiteHowItWorksRoute
  '/login': typeof SiteLoginRoute
  '/match': typeof SiteMatchRoute
  '/privacy': typeof SitePrivacyRoute
  '/search': typeof SiteSearchRoute
  '/submit': typeof SiteSubmitRoute
  '/terms': typeof SiteTermsRoute
  '/welcome': typeof SiteWelcomeRoute
  '/': typeof SiteIndexRoute
  '/admin/articles': typeof SiteAdminArticlesRoute
  '/claim/$slug': typeof SiteClaimSlugRoute
  '/provider/$slug': typeof SiteProviderSlugRoute
  '/review/$slug': typeof SiteReviewSlugRoute
  '/service/$slug': typeof SiteServiceSlugRoute
  '/style/$slug': typeof SiteStyleSlugRoute
  '/api/public/admin-seed-import': typeof ApiPublicAdminSeedImportRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/claim': typeof SiteClaimIndexRoute
  '/review': typeof SiteReviewIndexRoute
  '/admin/provider/$placeId': typeof SiteAdminProviderPlaceIdRoute
  '/dashboard/listing/$placeId': typeof SiteDashboardListingPlaceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_site/about': typeof SiteAboutRoute
  '/_site/admin': typeof SiteAdminRouteWithChildren
  '/_site/compare': typeof SiteCompareRoute
  '/_site/contact': typeof SiteContactRoute
  '/_site/dashboard': typeof SiteDashboardRouteWithChildren
  '/_site/favorites': typeof SiteFavoritesRoute
  '/_site/for-business': typeof SiteForBusinessRoute
  '/_site/how-it-works': typeof SiteHowItWorksRoute
  '/_site/login': typeof SiteLoginRoute
  '/_site/match': typeof SiteMatchRoute
  '/_site/privacy': typeof SitePrivacyRoute
  '/_site/search': typeof SiteSearchRoute
  '/_site/submit': typeof SiteSubmitRoute
  '/_site/terms': typeof SiteTermsRoute
  '/_site/welcome': typeof SiteWelcomeRoute
  '/_site/': typeof SiteIndexRoute
  '/_site/admin/articles': typeof SiteAdminArticlesRoute
  '/_site/claim/$slug': typeof SiteClaimSlugRoute
  '/_site/provider/$slug': typeof SiteProviderSlugRoute
  '/_site/review/$slug': typeof SiteReviewSlugRoute
  '/_site/service/$slug': typeof SiteServiceSlugRoute
  '/_site/style/$slug': typeof SiteStyleSlugRoute
  '/api/public/admin-seed-import': typeof ApiPublicAdminSeedImportRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/_site/claim/': typeof SiteClaimIndexRoute
  '/_site/review/': typeof SiteReviewIndexRoute
  '/_site/admin/provider/$placeId': typeof SiteAdminProviderPlaceIdRoute
  '/_site/dashboard/listing/$placeId': typeof SiteDashboardListingPlaceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/about'
    | '/admin'
    | '/compare'
    | '/contact'
    | '/dashboard'
    | '/favorites'
    | '/for-business'
    | '/how-it-works'
    | '/login'
    | '/match'
    | '/privacy'
    | '/search'
    | '/submit'
    | '/terms'
    | '/welcome'
    | '/admin/articles'
    | '/claim/$slug'
    | '/provider/$slug'
    | '/review/$slug'
    | '/service/$slug'
    | '/style/$slug'
    | '/api/public/admin-seed-import'
    | '/api/public/track'
    | '/claim/'
    | '/review/'
    | '/admin/provider/$placeId'
    | '/dashboard/listing/$placeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sitemap.xml'
    | '/about'
    | '/admin'
    | '/compare'
    | '/contact'
    | '/dashboard'
    | '/favorites'
    | '/for-business'
    | '/how-it-works'
    | '/login'
    | '/match'
    | '/privacy'
    | '/search'
    | '/submit'
    | '/terms'
    | '/welcome'
    | '/'
    | '/admin/articles'
    | '/claim/$slug'
    | '/provider/$slug'
    | '/review/$slug'
    | '/service/$slug'
    | '/style/$slug'
    | '/api/public/admin-seed-import'
    | '/api/public/track'
    | '/claim'
    | '/review'
    | '/admin/provider/$placeId'
    | '/dashboard/listing/$placeId'
  id:
    | '__root__'
    | '/_site'
    | '/sitemap.xml'
    | '/_site/about'
    | '/_site/admin'
    | '/_site/compare'
    | '/_site/contact'
    | '/_site/dashboard'
    | '/_site/favorites'
    | '/_site/for-business'
    | '/_site/how-it-works'
    | '/_site/login'
    | '/_site/match'
    | '/_site/privacy'
    | '/_site/search'
    | '/_site/submit'
    | '/_site/terms'
    | '/_site/welcome'
    | '/_site/'
    | '/_site/admin/articles'
    | '/_site/claim/$slug'
    | '/_site/provider/$slug'
    | '/_site/review/$slug'
    | '/_site/service/$slug'
    | '/_site/style/$slug'
    | '/api/public/admin-seed-import'
    | '/api/public/track'
    | '/_site/claim/'
    | '/_site/review/'
    | '/_site/admin/provider/$placeId'
    | '/_site/dashboard/listing/$placeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicAdminSeedImportRoute: typeof ApiPublicAdminSeedImportRoute
  ApiPublicTrackRoute: typeof ApiPublicTrackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/admin': {
      id: '/_site/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof SiteAdminRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/compare': {
      id: '/_site/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof SiteCompareRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/dashboard': {
      id: '/_site/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof SiteDashboardRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/favorites': {
      id: '/_site/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof SiteFavoritesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/for-business': {
      id: '/_site/for-business'
      path: '/for-business'
      fullPath: '/for-business'
      preLoaderRoute: typeof SiteForBusinessRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/how-it-works': {
      id: '/_site/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof SiteHowItWorksRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/login': {
      id: '/_site/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof SiteLoginRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/match': {
      id: '/_site/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof SiteMatchRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/privacy': {
      id: '/_site/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof SitePrivacyRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/search': {
      id: '/_site/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SiteSearchRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/submit': {
      id: '/_site/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SiteSubmitRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/terms': {
      id: '/_site/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof SiteTermsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/welcome': {
      id: '/_site/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof SiteWelcomeRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/admin/articles': {
      id: '/_site/admin/articles'
      path: '/articles'
      fullPath: '/admin/articles'
      preLoaderRoute: typeof SiteAdminArticlesRouteImport
      parentRoute: typeof SiteAdminRoute
    }
    '/_site/claim/': {
      id: '/_site/claim/'
      path: '/claim'
      fullPath: '/claim/'
      preLoaderRoute: typeof SiteClaimIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/claim/$slug': {
      id: '/_site/claim/$slug'
      path: '/claim/$slug'
      fullPath: '/claim/$slug'
      preLoaderRoute: typeof SiteClaimSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/provider/$slug': {
      id: '/_site/provider/$slug'
      path: '/provider/$slug'
      fullPath: '/provider/$slug'
      preLoaderRoute: typeof SiteProviderSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/review/': {
      id: '/_site/review/'
      path: '/review'
      fullPath: '/review/'
      preLoaderRoute: typeof SiteReviewIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/review/$slug': {
      id: '/_site/review/$slug'
      path: '/review/$slug'
      fullPath: '/review/$slug'
      preLoaderRoute: typeof SiteReviewSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/service/$slug': {
      id: '/_site/service/$slug'
      path: '/service/$slug'
      fullPath: '/service/$slug'
      preLoaderRoute: typeof SiteServiceSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/style/$slug': {
      id: '/_site/style/$slug'
      path: '/style/$slug'
      fullPath: '/style/$slug'
      preLoaderRoute: typeof SiteStyleSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/api/public/admin-seed-import': {
      id: '/api/public/admin-seed-import'
      path: '/api/public/admin-seed-import'
      fullPath: '/api/public/admin-seed-import'
      preLoaderRoute: typeof ApiPublicAdminSeedImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/track': {
      id: '/api/public/track'
      path: '/api/public/track'
      fullPath: '/api/public/track'
      preLoaderRoute: typeof ApiPublicTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/admin/provider/$placeId': {
      id: '/_site/admin/provider/$placeId'
      path: '/provider/$placeId'
      fullPath: '/admin/provider/$placeId'
      preLoaderRoute: typeof SiteAdminProviderPlaceIdRouteImport
      parentRoute: typeof SiteAdminRoute
    }
    '/_site/dashboard/listing/$placeId': {
      id: '/_site/dashboard/listing/$placeId'
      path: '/listing/$placeId'
      fullPath: '/dashboard/listing/$placeId'
      preLoaderRoute: typeof SiteDashboardListingPlaceIdRouteImport
      parentRoute: typeof SiteDashboardRoute
    }
  }
}

interface SiteAdminRouteChildren {
  SiteAdminArticlesRoute: typeof SiteAdminArticlesRoute
  SiteAdminProviderPlaceIdRoute: typeof SiteAdminProviderPlaceIdRoute
}

const SiteAdminRouteChildren: SiteAdminRouteChildren = {
  SiteAdminArticlesRoute: SiteAdminArticlesRoute,
  SiteAdminProviderPlaceIdRoute: SiteAdminProviderPlaceIdRoute,
}

const SiteAdminRouteWithChildren = SiteAdminRoute._addFileChildren(
  SiteAdminRouteChildren,
)

interface SiteDashboardRouteChildren {
  SiteDashboardListingPlaceIdRoute: typeof SiteDashboardListingPlaceIdRoute
}

const SiteDashboardRouteChildren: SiteDashboardRouteChildren = {
  SiteDashboardListingPlaceIdRoute: SiteDashboardListingPlaceIdRoute,
}

const SiteDashboardRouteWithChildren = SiteDashboardRoute._addFileChildren(
  SiteDashboardRouteChildren,
)

interface SiteRouteChildren {
  SiteAboutRoute: typeof SiteAboutRoute
  SiteAdminRoute: typeof SiteAdminRouteWithChildren
  SiteCompareRoute: typeof SiteCompareRoute
  SiteContactRoute: typeof SiteContactRoute
  SiteDashboardRoute: typeof SiteDashboardRouteWithChildren
  SiteFavoritesRoute: typeof SiteFavoritesRoute
  SiteForBusinessRoute: typeof SiteForBusinessRoute
  SiteHowItWorksRoute: typeof SiteHowItWorksRoute
  SiteLoginRoute: typeof SiteLoginRoute
  SiteMatchRoute: typeof SiteMatchRoute
  SitePrivacyRoute: typeof SitePrivacyRoute
  SiteSearchRoute: typeof SiteSearchRoute
  SiteSubmitRoute: typeof SiteSubmitRoute
  SiteTermsRoute: typeof SiteTermsRoute
  SiteWelcomeRoute: typeof SiteWelcomeRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SiteClaimSlugRoute: typeof SiteClaimSlugRoute
  SiteProviderSlugRoute: typeof SiteProviderSlugRoute
  SiteReviewSlugRoute: typeof SiteReviewSlugRoute
  SiteServiceSlugRoute: typeof SiteServiceSlugRoute
  SiteStyleSlugRoute: typeof SiteStyleSlugRoute
  SiteClaimIndexRoute: typeof SiteClaimIndexRoute
  SiteReviewIndexRoute: typeof SiteReviewIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAboutRoute: SiteAboutRoute,
  SiteAdminRoute: SiteAdminRouteWithChildren,
  SiteCompareRoute: SiteCompareRoute,
  SiteContactRoute: SiteContactRoute,
  SiteDashboardRoute: SiteDashboardRouteWithChildren,
  SiteFavoritesRoute: SiteFavoritesRoute,
  SiteForBusinessRoute: SiteForBusinessRoute,
  SiteHowItWorksRoute: SiteHowItWorksRoute,
  SiteLoginRoute: SiteLoginRoute,
  SiteMatchRoute: SiteMatchRoute,
  SitePrivacyRoute: SitePrivacyRoute,
  SiteSearchRoute: SiteSearchRoute,
  SiteSubmitRoute: SiteSubmitRoute,
  SiteTermsRoute: SiteTermsRoute,
  SiteWelcomeRoute: SiteWelcomeRoute,
  SiteIndexRoute: SiteIndexRoute,
  SiteClaimSlugRoute: SiteClaimSlugRoute,
  SiteProviderSlugRoute: SiteProviderSlugRoute,
  SiteReviewSlugRoute: SiteReviewSlugRoute,
  SiteServiceSlugRoute: SiteServiceSlugRoute,
  SiteStyleSlugRoute: SiteStyleSlugRoute,
  SiteClaimIndexRoute: SiteClaimIndexRoute,
  SiteReviewIndexRoute: SiteReviewIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicAdminSeedImportRoute: ApiPublicAdminSeedImportRoute,
  ApiPublicTrackRoute: ApiPublicTrackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
